version: '2'
services:
    jhipstergateway-app:
        image: jhipstergateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstergateway-mysql:3306/jhipstergateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstergateway-mysql:
        extends:
            file: mysql.yml
            service: jhipstergateway-mysql
